/* tslint:disable */
/* eslint-disable */
/**
 * MLOps API
 * API for image prediction and model management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageDto } from './ImageDto';
import {
    ImageDtoFromJSON,
    ImageDtoFromJSONTyped,
    ImageDtoToJSON,
    ImageDtoToJSONTyped,
} from './ImageDto';

/**
 * 
 * @export
 * @interface BatchDto
 */
export interface BatchDto {
    /**
     * Batch ID
     * @type {string}
     * @memberof BatchDto
     */
    id: string;
    /**
     * Batch status
     * @type {string}
     * @memberof BatchDto
     */
    status: BatchDtoStatusEnum;
    /**
     * Total number of images in the batch
     * @type {number}
     * @memberof BatchDto
     */
    totalImages: number;
    /**
     * Number of processed images
     * @type {number}
     * @memberof BatchDto
     */
    processedImages: number;
    /**
     * Number of successful predictions
     * @type {number}
     * @memberof BatchDto
     */
    successfulPredictions: number;
    /**
     * Number of failed predictions
     * @type {number}
     * @memberof BatchDto
     */
    failedPredictions: number;
    /**
     * Model name used for prediction
     * @type {string}
     * @memberof BatchDto
     */
    modelName?: string;
    /**
     * Progress percentage
     * @type {number}
     * @memberof BatchDto
     */
    progress: number;
    /**
     * Images in the batch
     * @type {Array<ImageDto>}
     * @memberof BatchDto
     */
    images?: Array<ImageDto>;
    /**
     * Creation date
     * @type {Date}
     * @memberof BatchDto
     */
    createdAt: Date;
    /**
     * Last update date
     * @type {Date}
     * @memberof BatchDto
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const BatchDtoStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type BatchDtoStatusEnum = typeof BatchDtoStatusEnum[keyof typeof BatchDtoStatusEnum];


/**
 * Check if a given object implements the BatchDto interface.
 */
export function instanceOfBatchDto(value: object): value is BatchDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('totalImages' in value) || value['totalImages'] === undefined) return false;
    if (!('processedImages' in value) || value['processedImages'] === undefined) return false;
    if (!('successfulPredictions' in value) || value['successfulPredictions'] === undefined) return false;
    if (!('failedPredictions' in value) || value['failedPredictions'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function BatchDtoFromJSON(json: any): BatchDto {
    return BatchDtoFromJSONTyped(json, false);
}

export function BatchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'totalImages': json['totalImages'],
        'processedImages': json['processedImages'],
        'successfulPredictions': json['successfulPredictions'],
        'failedPredictions': json['failedPredictions'],
        'modelName': json['modelName'] == null ? undefined : json['modelName'],
        'progress': json['progress'],
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(ImageDtoFromJSON)),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function BatchDtoToJSON(json: any): BatchDto {
    return BatchDtoToJSONTyped(json, false);
}

export function BatchDtoToJSONTyped(value?: BatchDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'totalImages': value['totalImages'],
        'processedImages': value['processedImages'],
        'successfulPredictions': value['successfulPredictions'],
        'failedPredictions': value['failedPredictions'],
        'modelName': value['modelName'],
        'progress': value['progress'],
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ImageDtoToJSON)),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

