/* tslint:disable */
/* eslint-disable */
/**
 * MLOps API
 * API for image prediction and model management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PredictionDto } from './PredictionDto';
import {
    PredictionDtoFromJSON,
    PredictionDtoFromJSONTyped,
    PredictionDtoToJSON,
    PredictionDtoToJSONTyped,
} from './PredictionDto';

/**
 * 
 * @export
 * @interface ImageDto
 */
export interface ImageDto {
    /**
     * Image ID
     * @type {string}
     * @memberof ImageDto
     */
    id: string;
    /**
     * Is training image
     * @type {boolean}
     * @memberof ImageDto
     */
    isTraining: boolean;
    /**
     * Original filename
     * @type {string}
     * @memberof ImageDto
     */
    filename?: string;
    /**
     * Image URL
     * @type {string}
     * @memberof ImageDto
     */
    imageUrl?: string;
    /**
     * Predictions for this image
     * @type {Array<PredictionDto>}
     * @memberof ImageDto
     */
    processeds: Array<PredictionDto>;
    /**
     * Creation date
     * @type {Date}
     * @memberof ImageDto
     */
    createdAt: Date;
    /**
     * Last update date
     * @type {Date}
     * @memberof ImageDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ImageDto interface.
 */
export function instanceOfImageDto(value: object): value is ImageDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isTraining' in value) || value['isTraining'] === undefined) return false;
    if (!('processeds' in value) || value['processeds'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ImageDtoFromJSON(json: any): ImageDto {
    return ImageDtoFromJSONTyped(json, false);
}

export function ImageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'isTraining': json['isTraining'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'processeds': ((json['processeds'] as Array<any>).map(PredictionDtoFromJSON)),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ImageDtoToJSON(json: any): ImageDto {
    return ImageDtoToJSONTyped(json, false);
}

export function ImageDtoToJSONTyped(value?: ImageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'isTraining': value['isTraining'],
        'filename': value['filename'],
        'imageUrl': value['imageUrl'],
        'processeds': ((value['processeds'] as Array<any>).map(PredictionDtoToJSON)),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

