/* tslint:disable */
/* eslint-disable */
/**
 * MLOps API
 * API for image prediction and model management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelDto
 */
export interface ModelDto {
    /**
     * Model run ID
     * @type {string}
     * @memberof ModelDto
     */
    id: string;
    /**
     * Model display name with metrics
     * @type {string}
     * @memberof ModelDto
     */
    name: string;
    /**
     * Model metrics
     * @type {object}
     * @memberof ModelDto
     */
    metrics: object;
    /**
     * Model parameters
     * @type {object}
     * @memberof ModelDto
     */
    params: object;
    /**
     * MLflow model URI (e.g., runs:/<run_id>/model)
     * @type {string}
     * @memberof ModelDto
     */
    uri: string;
    /**
     * Model creation timestamp
     * @type {number}
     * @memberof ModelDto
     */
    createdAt: number;
}

/**
 * Check if a given object implements the ModelDto interface.
 */
export function instanceOfModelDto(value: object): value is ModelDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('metrics' in value) || value['metrics'] === undefined) return false;
    if (!('params' in value) || value['params'] === undefined) return false;
    if (!('uri' in value) || value['uri'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ModelDtoFromJSON(json: any): ModelDto {
    return ModelDtoFromJSONTyped(json, false);
}

export function ModelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'metrics': json['metrics'],
        'params': json['params'],
        'uri': json['uri'],
        'createdAt': json['createdAt'],
    };
}

export function ModelDtoToJSON(json: any): ModelDto {
    return ModelDtoToJSONTyped(json, false);
}

export function ModelDtoToJSONTyped(value?: ModelDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'metrics': value['metrics'],
        'params': value['params'],
        'uri': value['uri'],
        'createdAt': value['createdAt'],
    };
}

