/* tslint:disable */
/* eslint-disable */
/**
 * MLOps API
 * API for image prediction and model management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelDto } from './ModelDto';
import {
    ModelDtoFromJSON,
    ModelDtoFromJSONTyped,
    ModelDtoToJSON,
    ModelDtoToJSONTyped,
} from './ModelDto';

/**
 * 
 * @export
 * @interface ModelsResponseDto
 */
export interface ModelsResponseDto {
    /**
     * List of available models
     * @type {Array<ModelDto>}
     * @memberof ModelsResponseDto
     */
    models: Array<ModelDto>;
    /**
     * Best model based on validation loss
     * @type {ModelDto}
     * @memberof ModelsResponseDto
     */
    bestModel: ModelDto | null;
}

/**
 * Check if a given object implements the ModelsResponseDto interface.
 */
export function instanceOfModelsResponseDto(value: object): value is ModelsResponseDto {
    if (!('models' in value) || value['models'] === undefined) return false;
    if (!('bestModel' in value) || value['bestModel'] === undefined) return false;
    return true;
}

export function ModelsResponseDtoFromJSON(json: any): ModelsResponseDto {
    return ModelsResponseDtoFromJSONTyped(json, false);
}

export function ModelsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'models': ((json['models'] as Array<any>).map(ModelDtoFromJSON)),
        'bestModel': ModelDtoFromJSON(json['bestModel']),
    };
}

export function ModelsResponseDtoToJSON(json: any): ModelsResponseDto {
    return ModelsResponseDtoToJSONTyped(json, false);
}

export function ModelsResponseDtoToJSONTyped(value?: ModelsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'models': ((value['models'] as Array<any>).map(ModelDtoToJSON)),
        'bestModel': ModelDtoToJSON(value['bestModel']),
    };
}

