/* tslint:disable */
/* eslint-disable */
/**
 * MLOps API
 * API for image prediction and model management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PredictionResultDto
 */
export interface PredictionResultDto {
    /**
     * Has beard
     * @type {boolean}
     * @memberof PredictionResultDto
     */
    beard: boolean;
    /**
     * Has mustache
     * @type {boolean}
     * @memberof PredictionResultDto
     */
    mustache: boolean;
    /**
     * Wears glasses
     * @type {boolean}
     * @memberof PredictionResultDto
     */
    glasses: boolean;
    /**
     * Hair color
     * @type {string}
     * @memberof PredictionResultDto
     */
    hairColor: PredictionResultDtoHairColorEnum;
    /**
     * Hair length
     * @type {string}
     * @memberof PredictionResultDto
     */
    hairLength: PredictionResultDtoHairLengthEnum;
}


/**
 * @export
 */
export const PredictionResultDtoHairColorEnum = {
    Blond: 'blond',
    LightBrown: 'lightBrown',
    Red: 'red',
    DarkBrown: 'darkBrown',
    GrayBlue: 'grayBlue'
} as const;
export type PredictionResultDtoHairColorEnum = typeof PredictionResultDtoHairColorEnum[keyof typeof PredictionResultDtoHairColorEnum];

/**
 * @export
 */
export const PredictionResultDtoHairLengthEnum = {
    Bald: 'bald',
    Short: 'short',
    Long: 'long'
} as const;
export type PredictionResultDtoHairLengthEnum = typeof PredictionResultDtoHairLengthEnum[keyof typeof PredictionResultDtoHairLengthEnum];


/**
 * Check if a given object implements the PredictionResultDto interface.
 */
export function instanceOfPredictionResultDto(value: object): value is PredictionResultDto {
    if (!('beard' in value) || value['beard'] === undefined) return false;
    if (!('mustache' in value) || value['mustache'] === undefined) return false;
    if (!('glasses' in value) || value['glasses'] === undefined) return false;
    if (!('hairColor' in value) || value['hairColor'] === undefined) return false;
    if (!('hairLength' in value) || value['hairLength'] === undefined) return false;
    return true;
}

export function PredictionResultDtoFromJSON(json: any): PredictionResultDto {
    return PredictionResultDtoFromJSONTyped(json, false);
}

export function PredictionResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictionResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'beard': json['beard'],
        'mustache': json['mustache'],
        'glasses': json['glasses'],
        'hairColor': json['hairColor'],
        'hairLength': json['hairLength'],
    };
}

export function PredictionResultDtoToJSON(json: any): PredictionResultDto {
    return PredictionResultDtoToJSONTyped(json, false);
}

export function PredictionResultDtoToJSONTyped(value?: PredictionResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'beard': value['beard'],
        'mustache': value['mustache'],
        'glasses': value['glasses'],
        'hairColor': value['hairColor'],
        'hairLength': value['hairLength'],
    };
}

