/* tslint:disable */
/* eslint-disable */
/**
 * MLOps API
 * API for image prediction and model management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PredictionResultDto } from './PredictionResultDto';
import {
    PredictionResultDtoFromJSON,
    PredictionResultDtoFromJSONTyped,
    PredictionResultDtoToJSON,
    PredictionResultDtoToJSONTyped,
} from './PredictionResultDto';

/**
 * 
 * @export
 * @interface PredictionDto
 */
export interface PredictionDto {
    /**
     * Prediction ID
     * @type {string}
     * @memberof PredictionDto
     */
    id: string;
    /**
     * Model name used for prediction
     * @type {string}
     * @memberof PredictionDto
     */
    model: string;
    /**
     * Prediction result
     * @type {PredictionResultDto}
     * @memberof PredictionDto
     */
    result: PredictionResultDto;
    /**
     * Creation date
     * @type {Date}
     * @memberof PredictionDto
     */
    createdAt: Date;
    /**
     * Last update date
     * @type {Date}
     * @memberof PredictionDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the PredictionDto interface.
 */
export function instanceOfPredictionDto(value: object): value is PredictionDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PredictionDtoFromJSON(json: any): PredictionDto {
    return PredictionDtoFromJSONTyped(json, false);
}

export function PredictionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'model': json['model'],
        'result': PredictionResultDtoFromJSON(json['result']),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function PredictionDtoToJSON(json: any): PredictionDto {
    return PredictionDtoToJSONTyped(json, false);
}

export function PredictionDtoToJSONTyped(value?: PredictionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'model': value['model'],
        'result': PredictionResultDtoToJSON(value['result']),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

