/* tslint:disable */
/* eslint-disable */
/**
 * MLOps API
 * API for image prediction and model management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadResponseDto
 */
export interface UploadResponseDto {
    /**
     * Success message
     * @type {string}
     * @memberof UploadResponseDto
     */
    message: string;
    /**
     * Batch ID for tracking progress
     * @type {string}
     * @memberof UploadResponseDto
     */
    batchId: string;
    /**
     * Number of images in the batch
     * @type {number}
     * @memberof UploadResponseDto
     */
    count: number;
}

/**
 * Check if a given object implements the UploadResponseDto interface.
 */
export function instanceOfUploadResponseDto(value: object): value is UploadResponseDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('batchId' in value) || value['batchId'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function UploadResponseDtoFromJSON(json: any): UploadResponseDto {
    return UploadResponseDtoFromJSONTyped(json, false);
}

export function UploadResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'batchId': json['batchId'],
        'count': json['count'],
    };
}

export function UploadResponseDtoToJSON(json: any): UploadResponseDto {
    return UploadResponseDtoToJSONTyped(json, false);
}

export function UploadResponseDtoToJSONTyped(value?: UploadResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'batchId': value['batchId'],
        'count': value['count'],
    };
}

