/* tslint:disable */
/* eslint-disable */
/**
 * MLOps API
 * API for image prediction and model management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BatchDto,
  ImageDto,
} from '../models/index';
import {
    BatchDtoFromJSON,
    BatchDtoToJSON,
    ImageDtoFromJSON,
    ImageDtoToJSON,
} from '../models/index';

export interface BatchControllerExportCSVRequest {
    id: string;
}

export interface BatchControllerFindAllRequest {
    limit?: number;
    offset?: number;
}

export interface BatchControllerFindOneRequest {
    id: string;
}

export interface BatchControllerGetBatchImagesRequest {
    id: string;
    limit?: number;
    offset?: number;
}

export interface BatchControllerGetStatisticsRequest {
    id: string;
}

/**
 * 
 */
export class BatchesApi extends runtime.BaseAPI {

    /**
     * Download all predictions for a batch in CSV format. Binary values (0/1) for Beard, Mustache, Glasses. Numeric indexes for Hair Color (0=blond, 1=lightBrown, 2=red, 3=darkBrown, 4=grayBlue) and Hair Length (0=bald, 1=short, 2=long).
     * Export batch results as CSV
     */
    async batchControllerExportCSVRaw(requestParameters: BatchControllerExportCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling batchControllerExportCSV().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/batches/{id}/export/csv`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download all predictions for a batch in CSV format. Binary values (0/1) for Beard, Mustache, Glasses. Numeric indexes for Hair Color (0=blond, 1=lightBrown, 2=red, 3=darkBrown, 4=grayBlue) and Hair Length (0=bald, 1=short, 2=long).
     * Export batch results as CSV
     */
    async batchControllerExportCSV(requestParameters: BatchControllerExportCSVRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.batchControllerExportCSVRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve all upload batches with pagination
     * Get all batches
     */
    async batchControllerFindAllRaw(requestParameters: BatchControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BatchDto>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/batches`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BatchDtoFromJSON));
    }

    /**
     * Retrieve all upload batches with pagination
     * Get all batches
     */
    async batchControllerFindAll(requestParameters: BatchControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BatchDto>> {
        const response = await this.batchControllerFindAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a specific batch with basic info (without images)
     * Get batch by ID
     */
    async batchControllerFindOneRaw(requestParameters: BatchControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling batchControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/batches/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchDtoFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific batch with basic info (without images)
     * Get batch by ID
     */
    async batchControllerFindOne(requestParameters: BatchControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchDto> {
        const response = await this.batchControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve images from a specific batch with pagination
     * Get batch images with pagination
     */
    async batchControllerGetBatchImagesRaw(requestParameters: BatchControllerGetBatchImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ImageDto>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling batchControllerGetBatchImages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/batches/{id}/images`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ImageDtoFromJSON));
    }

    /**
     * Retrieve images from a specific batch with pagination
     * Get batch images with pagination
     */
    async batchControllerGetBatchImages(requestParameters: BatchControllerGetBatchImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ImageDto>> {
        const response = await this.batchControllerGetBatchImagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve progress and statistics for a specific batch
     * Get batch statistics
     */
    async batchControllerGetStatisticsRaw(requestParameters: BatchControllerGetStatisticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling batchControllerGetStatistics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/batches/{id}/statistics`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchDtoFromJSON(jsonValue));
    }

    /**
     * Retrieve progress and statistics for a specific batch
     * Get batch statistics
     */
    async batchControllerGetStatistics(requestParameters: BatchControllerGetStatisticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchDto> {
        const response = await this.batchControllerGetStatisticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
