/* tslint:disable */
/* eslint-disable */
/**
 * MLOps API
 * API for image prediction and model management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ImageDto,
  PredictionDto,
} from '../models/index';
import {
    ImageDtoFromJSON,
    ImageDtoToJSON,
    PredictionDtoFromJSON,
    PredictionDtoToJSON,
} from '../models/index';

export interface ImagesControllerFindAllRequest {
    limit?: number;
    offset?: number;
    beard?: boolean;
    mustache?: boolean;
    glasses?: boolean;
    hairColor?: ImagesControllerFindAllHairColorEnum;
    hairLength?: ImagesControllerFindAllHairLengthEnum;
}

export interface ImagesControllerFindOneRequest {
    id: string;
}

export interface ImagesControllerGetImageFileRequest {
    filename: string;
}

export interface ImagesControllerGetImagePredictionsRequest {
    id: string;
}

/**
 * 
 */
export class ImagesApi extends runtime.BaseAPI {

    /**
     * Retrieve all uploaded images with their predictions
     * Get all images
     */
    async imagesControllerFindAllRaw(requestParameters: ImagesControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ImageDto>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['beard'] != null) {
            queryParameters['beard'] = requestParameters['beard'];
        }

        if (requestParameters['mustache'] != null) {
            queryParameters['mustache'] = requestParameters['mustache'];
        }

        if (requestParameters['glasses'] != null) {
            queryParameters['glasses'] = requestParameters['glasses'];
        }

        if (requestParameters['hairColor'] != null) {
            queryParameters['hairColor'] = requestParameters['hairColor'];
        }

        if (requestParameters['hairLength'] != null) {
            queryParameters['hairLength'] = requestParameters['hairLength'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/images`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ImageDtoFromJSON));
    }

    /**
     * Retrieve all uploaded images with their predictions
     * Get all images
     */
    async imagesControllerFindAll(requestParameters: ImagesControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ImageDto>> {
        const response = await this.imagesControllerFindAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a specific image with all its predictions
     * Get image by ID
     */
    async imagesControllerFindOneRaw(requestParameters: ImagesControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling imagesControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/images/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageDtoFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific image with all its predictions
     * Get image by ID
     */
    async imagesControllerFindOne(requestParameters: ImagesControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageDto> {
        const response = await this.imagesControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the actual image file by filename
     * Get image file
     */
    async imagesControllerGetImageFileRaw(requestParameters: ImagesControllerGetImageFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['filename'] == null) {
            throw new runtime.RequiredError(
                'filename',
                'Required parameter "filename" was null or undefined when calling imagesControllerGetImageFile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/images/file/{filename}`;
        urlPath = urlPath.replace(`{${"filename"}}`, encodeURIComponent(String(requestParameters['filename'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieve the actual image file by filename
     * Get image file
     */
    async imagesControllerGetImageFile(requestParameters: ImagesControllerGetImageFileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.imagesControllerGetImageFileRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve all predictions for a specific image
     * Get predictions for an image
     */
    async imagesControllerGetImagePredictionsRaw(requestParameters: ImagesControllerGetImagePredictionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PredictionDto>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling imagesControllerGetImagePredictions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/images/{id}/predictions`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PredictionDtoFromJSON));
    }

    /**
     * Retrieve all predictions for a specific image
     * Get predictions for an image
     */
    async imagesControllerGetImagePredictions(requestParameters: ImagesControllerGetImagePredictionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PredictionDto>> {
        const response = await this.imagesControllerGetImagePredictionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ImagesControllerFindAllHairColorEnum = {
    Blond: 'blond',
    LightBrown: 'lightBrown',
    Red: 'red',
    DarkBrown: 'darkBrown',
    GrayBlue: 'grayBlue'
} as const;
export type ImagesControllerFindAllHairColorEnum = typeof ImagesControllerFindAllHairColorEnum[keyof typeof ImagesControllerFindAllHairColorEnum];
/**
 * @export
 */
export const ImagesControllerFindAllHairLengthEnum = {
    Bald: 'bald',
    Short: 'short',
    Long: 'long'
} as const;
export type ImagesControllerFindAllHairLengthEnum = typeof ImagesControllerFindAllHairLengthEnum[keyof typeof ImagesControllerFindAllHairLengthEnum];
