/* tslint:disable */
/* eslint-disable */
/**
 * MLOps API
 * API for image prediction and model management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelsResponseDto,
} from '../models/index';
import {
    ModelsResponseDtoFromJSON,
    ModelsResponseDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class ModelsApi extends runtime.BaseAPI {

    /**
     * Get available MLflow models
     */
    async modelsControllerGetModelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/models`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get available MLflow models
     */
    async modelsControllerGetModels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsResponseDto> {
        const response = await this.modelsControllerGetModelsRaw(initOverrides);
        return await response.value();
    }

}
