/* tslint:disable */
/* eslint-disable */
/**
 * MLOps API
 * API for image prediction and model management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PredictionDto,
} from '../models/index';
import {
    PredictionDtoFromJSON,
    PredictionDtoToJSON,
} from '../models/index';

export interface PredictionsControllerFindAllRequest {
    limit?: number;
    offset?: number;
}

export interface PredictionsControllerFindOneRequest {
    id: string;
}

/**
 * 
 */
export class PredictionsApi extends runtime.BaseAPI {

    /**
     * Retrieve all prediction results with pagination support
     * Get all predictions
     */
    async predictionsControllerFindAllRaw(requestParameters: PredictionsControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PredictionDto>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/predictions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PredictionDtoFromJSON));
    }

    /**
     * Retrieve all prediction results with pagination support
     * Get all predictions
     */
    async predictionsControllerFindAll(requestParameters: PredictionsControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PredictionDto>> {
        const response = await this.predictionsControllerFindAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a specific prediction by its ID
     * Get prediction by ID
     */
    async predictionsControllerFindOneRaw(requestParameters: PredictionsControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PredictionDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling predictionsControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/predictions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PredictionDtoFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific prediction by its ID
     * Get prediction by ID
     */
    async predictionsControllerFindOne(requestParameters: PredictionsControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PredictionDto> {
        const response = await this.predictionsControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
