/* tslint:disable */
/* eslint-disable */
/**
 * MLOps API
 * API for image prediction and model management
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UploadResponseDto,
} from '../models/index';
import {
    UploadResponseDtoFromJSON,
    UploadResponseDtoToJSON,
} from '../models/index';

export interface UploadControllerUploadImagesRequest {
    file: Blob;
    modelName?: string;
}

/**
 * 
 */
export class UploadApi extends runtime.BaseAPI {

    /**
     * Upload a single image or a ZIP archive containing multiple images. Images will be processed and sent for ML prediction.
     * Upload image(s) for prediction
     */
    async uploadControllerUploadImagesRaw(requestParameters: UploadControllerUploadImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadResponseDto>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadControllerUploadImages().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['modelName'] != null) {
            formParams.append('modelName', requestParameters['modelName'] as any);
        }


        let urlPath = `/upload/images`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadResponseDtoFromJSON(jsonValue));
    }

    /**
     * Upload a single image or a ZIP archive containing multiple images. Images will be processed and sent for ML prediction.
     * Upload image(s) for prediction
     */
    async uploadControllerUploadImages(requestParameters: UploadControllerUploadImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadResponseDto> {
        const response = await this.uploadControllerUploadImagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
